"use client";

import { ProtectedRoute } from "@/components/auth/protected-route";
import { SafeImage } from "@/components/shared/safe-image";
import { ConfirmModal } from "@/components/shared/confirm-modal";
import { EmptyState } from "@/components/shared/empty-state";
import { ErrorState } from "@/components/shared/error-state";
import { LoadingSpinner } from "@/components/shared/loading-spinner";
import { bookingService } from "@/services/bookings";
import type { Booking, Room } from "@/types/api";
import { CalendarDays, Clock, StickyNote } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";

function roomOf(booking: Booking): Room | null { return typeof booking.room === "object" ? booking.room : null; }
function passed(booking: Booking) { return new Date(`${booking.date.slice(0, 10)}T${booking.endTime}:00`).getTime() < Date.now(); }
export default function MyBookingsPage() {
  const [bookings, setBookings] = useState<Booking[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [cancelling, setCancelling] = useState<Booking | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setBookings(await bookingService.mine()); } catch (value) { setError(value instanceof Error ? value.message : "Could not load your bookings"); } finally { setLoading(false); } }, []); useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function cancel() { if (!cancelling) return; setBusy(true); try { await bookingService.cancel(cancelling._id); setBookings((current) => current.map((item) => item._id === cancelling._id ? { ...item, status: "cancelled" } : item)); setCancelling(null); toast.success("Booking cancelled"); } catch (value) { toast.error(value instanceof Error ? value.message : "Could not cancel booking"); } finally { setBusy(false); } }
  return <ProtectedRoute><section className="page-section"><div className="container-shell"><p className="eyebrow">Your study schedule</p><h1 className="page-title mt-4">My Bookings</h1>{loading ? <LoadingSpinner label="Loading your bookings…"/> : error ? <div className="mt-10"><ErrorState message={error} onRetry={load}/></div> : bookings.length ? <div className="mt-10 grid gap-5">{bookings.map((booking) => { const room = roomOf(booking); return <article key={booking._id} className="grid overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-sm sm:grid-cols-[13rem_1fr]"><div className="relative min-h-48 bg-stone-200"><SafeImage src={room?.image || "/room-placeholder.svg"} alt={room ? room.roomName : "Booked study room"} fill className="object-cover" sizes="208px"/></div><div className="flex flex-col p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-serif text-2xl font-semibold">{room?.roomName ?? "Study room"}</h2><p className="mt-1 text-sm font-bold text-amber-800">${Number(booking.totalCost ?? booking.cost ?? 0).toFixed(2)} total</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold capitalize ${booking.status.toLowerCase() === "cancelled" ? "bg-stone-200 text-stone-600" : "bg-emerald-100 text-emerald-800"}`}>{booking.status}</span></div><div className="mt-5 flex flex-wrap gap-x-6 gap-y-3 text-sm text-stone-600"><span className="flex items-center gap-2"><CalendarDays className="size-4 text-amber-700"/>{new Date(`${booking.date.slice(0,10)}T00:00:00`).toLocaleDateString(undefined, { dateStyle: "medium" })}</span><span className="flex items-center gap-2"><Clock className="size-4 text-amber-700"/>{booking.startTime}–{booking.endTime}</span>{booking.specialNote && <span className="flex items-center gap-2"><StickyNote className="size-4 text-amber-700"/>{booking.specialNote}</span>}</div>{booking.status.toLowerCase() === "confirmed" && !passed(booking) && <button onClick={() => setCancelling(booking)} className="btn-secondary mt-6 self-start text-red-700">Cancel Booking</button>}</div></article>; })}</div> : <div className="mt-10"><EmptyState title="You have no bookings yet." description="Find a room that fits your next focused session." action="Explore rooms" href="/rooms"/></div>}</div></section><ConfirmModal open={Boolean(cancelling)} title="Cancel this booking?" description="Your reservation will be marked as cancelled and this time slot may become available to others." confirmLabel="Cancel Booking" busy={busy} onClose={() => setCancelling(null)} onConfirm={cancel}/></ProtectedRoute>;
}
